name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Copy pyproject
      run: |
        sed -i "s|.*version.*|version = `git tag -l | sed -n 1p`|g" pyproject.toml 
        cp pyproject.toml src/pyproject.toml

    - name: Check Package
      run: |
        poetry check
    - name: Install
      run: poetry install
    - name: Build package
      run: poetry build
    - name: Publish
      run: |
        poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
